#!/bin/bash
#PBS -l walltime=0:45:00
#PBS -l select=1:ncpus=10:mpiprocs=10:mem=270GB
#PBS -N density_assignment
#PBS -o out_file.txt
#PBS -e err_file.txt
cd $PBS_O_WORKDIR
echo Hello > hello.txt
export PYTHONPATH="$PYTHONPATH:/mnt/home/student/cprem/project-alpha-peak/code/library"
mpirun -np 10 python assign_density.py --snapdir /scratch/aseem/sims/bdm_cdm1024/r1/ --range 0 201 20 --scheme TSC --grid_size 512 --Pk --slice2D --outdir /mnt/home/student/cprem/myscratch/bdm_cdm1024/
