#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l select=2:ncpus=10:mem=50GB
#PBS -N visualise_halo_history
#PBS -m abe
#PBS -M premv@iucaa.in

cd $PBS_O_WORKDIR
source ~/.bashrc
conda activate conforg
### python39forge --version
parallel --sshloginfile $PBS_NODEFILE  -j 3 "cd $PBS_O_WORKDIR; source ~/.bashrc; conda activate conforg; python visualise.py --max_halos 1000 --M_around {1} --simname bdm_cdm1024 --downsample 8 --align {2}" :::  2e11 3e12 1e14 ::: 0 1
